image: alpine:latest

stages:
  - test

run_grpv_tests_on_kempar:
  stage: test
  script:
    - apk update
    - apk add openssh sshpass
    - export
    - sshpass -p $CI_PASSWORD ssh -oStrictHostKeyChecking=no $CI_USER@$CI_HOST "\
       cd /home/jade/cfri-workspace/uhd-build/examples &&\
       ./tx_waveforms --rate 1e6 --freq 15e6 --wave-type SINE --wave-freq 100e3 --channels 0,1,2,3 --nsamps 10000000\
       "
       
  only:
    - master-testing
