#!/bin/bash

if [ $# -lt 1 ]
then
	echo "Usage : $0 dig | rx | tx | synth | all"
	exit
fi

if [ "$1" != 'synth' ] && [ "$1" != 'tx' ] && [ "$1" != 'rx' ] && [ "$1" != 'dig' ] && [ "$1" != 'all' ]
then
	echo "- invalid argument"
	echo "- Usage : $0 dig | rx | tx | synth | all"	
	exit
fi

if [ "$1" = 'synth' ] || [ "$1" = 'all' ]
then
	echo "-- Press <ENTER> when ready to program the synth board --"
	read
	sudo avrdude -e -c avrispmkII -B 8 -p x256a3u -P usb -U application:w:synth.hex
	echo "-- Finished programming the synth board --"
fi

if [ "$1" = 'rx' ] || [ "$1" = 'all' ]
then
	echo "-- Press <ENTER> when ready to program the rx board --"
	read
	sudo avrdude -e -c avrispmkII -B 8 -p x256a3u -P usb -U application:w:rx.hex
	echo "-- Finished programming the rx board --"
fi

if [ "$1" = 'tx' ] || [ "$1" = 'all' ]
then
	echo "-- Press <ENTER> when ready to program the tx board --"
	read
	sudo avrdude -e -c avrispmkII -B 8 -p x256a3u -P usb -U application:w:tx.hex
	echo "-- Finished programming the tx board --"
fi

if [ "$1" = 'dig' ] || [ "$1" = 'all' ]
then
	echo "-- Press <ENTER> when ready to program the dig board --"
	read
	sudo avrdude -e -c avrispmkII -B 8 -p x256a3u -P usb -U application:w:dig.hex
	echo "-- Finished programming the dig board --"
fi
